spring:
  application:
    name: FlipDeal-Backend
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          from: 
          auth: true
          starttls:
            enable: true
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/DB_NAME
    username:  
    password: 
jwt:
  private-key: classpath:jwt/app.key
  public-key: classpath:jwt/app.pub
  access-token-ttl: 5m
  refresh-token-ttl: 1d

email-verification:
  base-url: http://localhost:8080/api/auth/email/verify?uid=%s&t=%s
  required: true

otp:
  email-verification:
    cache-prefix: otp:email-verification:%s
    ttl: 5m
    characters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
    length: 50

aws:
  access:
    key: 
  secret:
    key: 
  region: 
  s3:
    bucketname: 

razorpay_key: 
razorpay_secret: 